export const ERROR_CODES = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  CREATE_USER_ERROR: "CREATE_USER_ERROR",
  GET_USERS_ERROR: "GET_USERS_ERROR",
  MISSING_USER_ID: "MISSING_USER_ID",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  UPDATE_USER_ERROR: "UPDATE_USER_ERROR",
  DELETE_USER_ERROR: "DELETE_USER_ERROR",
  CREATE_PRODUCT_ERROR: "CREATE_PRODUCT_ERROR",
  GET_PRODUCTS_ERROR: "GET_PRODUCTS_ERROR",
  MISSING_PRODUCT_ID: "MISSING_PRODUCT_ID",
  PRODUCT_NOT_FOUND: "PRODUCT_NOT_FOUND",
  UPDATE_PRODUCT_ERROR: "UPDATE_PRODUCT_ERROR",
  DELETE_PRODUCT_ERROR: "DELETE_PRODUCT_ERROR",
  CREATE_PURCHASE_ERROR: "CREATE_PURCHASE_ERROR",
  GET_PURCHASES_ERROR: "GET_PURCHASES_ERROR",
  MISSING_PURCHASE_ID: "MISSING_PURCHASE_ID",
  PURCHASE_NOT_FOUND: "PURCHASE_NOT_FOUND",
  UPDATE_PURCHASE_ERROR: "UPDATE_PURCHASE_ERROR",
  NO_PURCHASES_FOUND: "NO_PURCHASES_FOUND",
  DELETE_PURCHASE_ERROR: "DELETE_PURCHASE_ERROR",
};

export const ERROR_MESSAGES = {
  VALIDATION_ERROR: "Required fields are missing.",
  CREATE_USER_ERROR: "An error occurred while creating the user.",
  GET_USERS_ERROR: "An error occurred while fetching users.",
  MISSING_USER_ID: "User ID is required.",
  USER_NOT_FOUND: (id: string) => `No user found with ID: ${id}`,
  UPDATE_USER_ERROR: "An error occurred while updating the user.",
  DELETE_USER_ERROR: "An error occurred while deleting the user.",
  NO_USERS_FOUND: "No users were found in the database.",
  NO_PRODUCTS_FOUND: "No products were found.",
  CREATE_PRODUCT_ERROR: "An error occurred while creating the product.",
  GET_PRODUCTS_ERROR: "An error occurred while fetching the products.",
  MISSING_PRODUCT_ID: "Product ID is required.",
  PRODUCT_NOT_FOUND: (id: string) => `No product found with ID: ${id}`,
  UPDATE_PRODUCT_ERROR: "An error occurred while updating the product.",
  DELETE_PRODUCT_ERROR: "An error occurred while deleting the product.",
  NO_PURCHASES_FOUND: "No purchases were found.",
  CREATE_PURCHASE_ERROR: "An error occurred while creating the purchase.",
  GET_PURCHASES_ERROR: "An error occurred while fetching purchases.",
  MISSING_PURCHASE_ID: "Purchase ID is required.",
  PURCHASE_NOT_FOUND: (id: string) => `No purchase found with ID: ${id}`,
  UPDATE_PURCHASE_ERROR: "An error occurred while updating the purchase.",
  DELETE_PURCHASE_ERROR: "An error occurred while deleting the purchase.",
};
